#!/bin/bash

# Stop Nginx if it's already running
service nginx stop

# Modify the Nginx configuration to run as nginx user and listen on port 8080
sed -i 's/user www-data;/user nginx;/g' /etc/nginx/nginx.conf
sed -i 's/listen 80;/listen 8080;/g' /etc/nginx/sites-enabled/default

# Start Nginx
service nginx start
